version: '2'
services:
    es:
      container_name: es
      image: 'hzwangmeng/es'
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        web:
          ipv4_address: 192.168.2.1
      volumes:
        - ./es/data/:/usr/share/elasticsearch/data:rw
        - ./es/log/:/usr/share/elasticsearch/logs:rw
      dns: 192.168.1.1
      hostname: es
      restart: always

    face-ai-web:
      container_name: face-ai-web
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - "8000:8000"
        - "5000:5000"
      volumes:
        - ./files/:/code/files:rw
        - ./filescopy/:/code/filescopy:rw
        - ./logs/:/code/logs:rw
      networks:
        web:
          ipv4_address: 192.168.2.2
      hostname: face-ai-web
      restart: always

networks:
  web:
    driver: 'bridge'
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.254
